version: "3.9"

services:
  benchmark_couchdb:
    image: couchdb:latest
    restart: always
    environment:
      - COUCHDB_USER=root
      - COUCHDB_PASSWORD=root
    volumes:
        - ../DbBenchmark.Container/couchdb:/opt/couchdb/data
    ports:
      - "5984:5984"
  
  benchmark_influxdb:
    image: influxdb:2.6-alpine
    restart: always
    environment:
      - INFLUXDB_DB=benchmark
      - INFLUXDB_ADMIN_USER=root
      - INFLUXDB_ADMIN_PASSWORD=root
    ports:
      - '8086:8086'
    volumes:
      - ../DbBenchmark.Container/database/influxdb:/var/lib/influxdb
