version: "3.9"

services:
  benchmark_couchdb:
    image: couchdb:latest
    restart: always
    environment:
      - COUCHDB_USER=root
      - COUCHDB_PASSWORD=root
    volumes:
      - ../DbBenchmark.Container/couchdb:/opt/couchdb/data
    ports:
      - "5984:5984"
  
  benchmark_influxdb:
    image: influxdb:2.6-alpine
    restart: always
    environment:
      - INFLUXDB_DB=benchmark
      - INFLUXDB_ADMIN_USER=root
      - INFLUXDB_ADMIN_PASSWORD=root
    ports:
      - '8086:8086'
    volumes:
      - ../DbBenchmark.Container/influxdb:/var/lib/influxdb

  benchmark_mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_password=root
    ports:
      - '27017:27017'
    volumes:
      - ../DbBenchmark.Container/mongodb:/data/db
  
  benchmark_redis_stack:
    image: redis/redis-stack:latest
    restart: always
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      - ../DbBenchmark.Container/redis:/data