version: "3.9"

services:  
  benchmark_couchdb:
    image: apache/couchdb:3
    restart: always
    environment:
      - COUCHDB_USER=root
      - COUCHDB_PASSWORD=root
    volumes:
      - ../DbBenchmark.Container/couchdb:/opt/couchdb/data
    ports:
      - '5984:5984'
  
  benchmark_influxdb:
    image: influxdb:2.6-alpine
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=rubert
      - DOCKER_INFLUXDB_INIT_PASSWORD=influx12
      - DOCKER_INFLUXDB_INIT_ORG=benchmark
      - DOCKER_INFLUXDB_INIT_BUCKET=benchmark
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=ibsu8H0W9WBNMTzlEfGGWmS5UAG6QJ0QBRPc6uECm_qn39bwy8jT0K3-eqVRLhvZbCdxPpv18yBHKOcqGDNt5w==
    ports:
      - '8086:8086'
    volumes:
      - ../DbBenchmark.Container/influxdb:/var/lib/influxdb2

  benchmark_mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - '17017:27017'
    volumes:
      - ../DbBenchmark.Container/mongodb:/data/db

  benchmark_redis_stack:
    image: redis/redis-stack:latest
    restart: always
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      - ../DbBenchmark.Container/redis:/data
