version: "3.9"

services:
  benchmark_couchdb:
    image: couchdb:latest
    restart: always
    environment:
      - COUCHDB_USER=root
      - COUCHDB_PASSWORD=root
    volumes:
        - ../DbBenchmark.Container/couchdb:/opt/couchdb/data
    ports:
      - "5984:5984"