imports:
  - ./BenchmarkFiles/LoadGenerators/bombardier.yml

jobs:
  server:
    source:
      localFolder: ../
      project: DbBenchmark/DbBenchmark.csproj
      selfContained: false
    dotnetTrace: true
    options:
      collectCounters: true
      traceOutput: couchdb_trace

scenarios:
  bomb:
    application:
      job: server
    load:
      job: bombardier
      variables:
        serverPort: 5000
        path: /Benchmark/CouchDb

profiles:
  local:
    variables:
      serverAddress: localhost
    jobs:
      application:
        endpoints:
          - http://localhost:5010
      load:
        endpoints:
          - http://localhost:5010