imports:
  - ./BenchmarkFiles/LoadGenerators/bombardier.yml

jobs:
  server:
    source:
      localFolder: ../
      project: DbBenchmark/DbBenchmark.csproj
      selfContained: false

scenarios:
  bomb:
    application:
      job: server
    load:
      job: bombardier
      variables:
        serverPort: 5000
        path: /Benchmark/RedisTimeSeries

profiles:
  fourtress:
    variables:
      serverAddress: 172.16.10.23
    jobs:
      application:
        endpoints:
          - http://172.16.10.23:5010
      load:
        endpoints:
          - http://172.16.10.23:5010      
  local:
    variables:
      serverAddress: localhost
    jobs:
      application:
        endpoints:
          - http://localhost:5010
      load:
        endpoints:
          - http://localhost:5010